DROP TABLE IF EXISTS 'people';

CREATE TABLE `people` (
  `pid` int(11) NOT NULL AUTO_INCREMENT,
  `entering` int(11) NOT NULL,
  `eventTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`pid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;
